repos:
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.5.1
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject

  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff format
        entry: uv
        args: [run, ruff, format]
        language: system
        types: [python]
        pass_filenames: true
        always_run: false
      - id: ruff-check
        name: Ruff lint
        entry: uv
        args: [run, ruff, check, --fix, --exit-non-zero-on-fix]
        language: system
        types: [python]
        pass_filenames: true
        always_run: false
      - id: pycodestyle
        name: PEP8 style check (pycodestyle)
        entry: uv
        args: ["run", "pycodestyle", "--max-line-length=88", "--ignore=E203,E501,W503,E704"]
        language: system
        types: [python]
        pass_filenames: true
        always_run: false
      - id: pyright
        name: Type check with Pyright (strict)
        entry: uv
        args: [run, pyright]
        language: system
        types: [python]
        pass_filenames: true
        always_run: false
