name: Build and Test Binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install 3.12
    
    - name: Install dependencies
      run: uv sync --extra dev
    
    - name: Build binary
      run: |
        uv add --dev pyinstaller
        uv run python build.py
      env:
        LITELLM_API_KEY: "dummy-key-for-testing"
        LITELLM_MODEL: "gpt-3.5-turbo"
    
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: openhands-server-${{ matrix.os }}
        path: |
          dist/openhands-server*
        retention-days: 7
